export interface Palette {
  name: string
  colors: [string, string, string]
  vars: Record<string, string>
  darkVars: Record<string, string>
}

export const PALETTES: Palette[] = [
  { name: 'Default', colors: ['#3B82F6', '#60A5FA', '#EFF6FF'],
    vars: { '--accent': '#3B82F6', '--accent-light': '#EFF6FF' },
    darkVars: { '--accent': '#60A5FA', '--accent-light': '#1E3A5F' } },
  { name: 'Ocean', colors: ['#0EA5E9', '#38BDF8', '#F0F9FF'],
    vars: { '--accent': '#0EA5E9', '--accent-light': '#F0F9FF' },
    darkVars: { '--accent': '#38BDF8', '--accent-light': '#0C4A6E' } },
  { name: 'Midnight', colors: ['#1E40AF', '#3B82F6', '#EFF6FF'],
    vars: { '--accent': '#1E40AF', '--accent-light': '#EFF6FF' },
    darkVars: { '--accent': '#3B82F6', '--accent-light': '#172554' } },
  { name: 'Lavender', colors: ['#8B5CF6', '#A78BFA', '#F5F3FF'],
    vars: { '--accent': '#8B5CF6', '--accent-light': '#F5F3FF' },
    darkVars: { '--accent': '#A78BFA', '--accent-light': '#3B0764' } },
  { name: 'Periwinkle', colors: ['#6B7FD4', '#8B9FE8', '#F0F2FD'],
    vars: { '--accent': '#6B7FD4', '--accent-light': '#F0F2FD' },
    darkVars: { '--accent': '#8B9FE8', '--accent-light': '#0A0E3D' } },
  { name: 'Rose', colors: ['#E11D48', '#FB7185', '#FFF1F2'],
    vars: { '--accent': '#E11D48', '--accent-light': '#FFF1F2' },
    darkVars: { '--accent': '#FB7185', '--accent-light': '#4C0519' } },
  { name: 'Sakura', colors: ['#D4859A', '#E8A0B0', '#FDF0F3'],
    vars: { '--accent': '#D4859A', '--accent-light': '#FDF0F3' },
    darkVars: { '--accent': '#E8A0B0', '--accent-light': '#3D1A22' } },
  { name: 'Dusty Rose', colors: ['#B07080', '#C99AAA', '#FAF0F2'],
    vars: { '--accent': '#B07080', '--accent-light': '#FAF0F2' },
    darkVars: { '--accent': '#C99AAA', '--accent-light': '#2E1018' } },
  { name: 'Lychee', colors: ['#E8607A', '#F08090', '#FEF0F2'],
    vars: { '--accent': '#E8607A', '--accent-light': '#FEF0F2' },
    darkVars: { '--accent': '#F08090', '--accent-light': '#3D0510' } },
  { name: 'Milkshake', colors: ['#E8A0C0', '#F0C0D8', '#FDF5FA'],
    vars: { '--accent': '#E8A0C0', '--accent-light': '#FDF5FA' },
    darkVars: { '--accent': '#F0C0D8', '--accent-light': '#3D0A22' } },
  { name: 'Sunset', colors: ['#F97316', '#FB923C', '#FFF7ED'],
    vars: { '--accent': '#F97316', '--accent-light': '#FFF7ED' },
    darkVars: { '--accent': '#FB923C', '--accent-light': '#7C2D12' } },
  { name: 'Cheesecake', colors: ['#C4A265', '#D4B885', '#FDF8EF'],
    vars: { '--accent': '#C4A265', '--accent-light': '#FDF8EF' },
    darkVars: { '--accent': '#D4B885', '--accent-light': '#2E200A' } },
  { name: 'Oat Milk', colors: ['#C8A882', '#D8C0A0', '#FAF6F0'],
    vars: { '--accent': '#C8A882', '--accent-light': '#FAF6F0' },
    darkVars: { '--accent': '#D8C0A0', '--accent-light': '#2E1E08' } },
  { name: 'Mocha', colors: ['#8B5E3C', '#A87850', '#FBF5F0'],
    vars: { '--accent': '#8B5E3C', '--accent-light': '#FBF5F0' },
    darkVars: { '--accent': '#A87850', '--accent-light': '#1E0E05' } },
  { name: 'Matcha', colors: ['#5C7A5C', '#8FAF8F', '#F0F5F0'],
    vars: { '--accent': '#5C7A5C', '--accent-light': '#F0F5F0' },
    darkVars: { '--accent': '#8FAF8F', '--accent-light': '#1A2E1A' } },
  { name: 'Eucalyptus', colors: ['#4A8C7F', '#6BB5A6', '#EDF5F4'],
    vars: { '--accent': '#4A8C7F', '--accent-light': '#EDF5F4' },
    darkVars: { '--accent': '#6BB5A6', '--accent-light': '#0F2926' } },
  { name: 'Pistachio', colors: ['#8DB870', '#ADDC90', '#F4FAF0'],
    vars: { '--accent': '#8DB870', '--accent-light': '#F4FAF0' },
    darkVars: { '--accent': '#ADDC90', '--accent-light': '#142A08' } },
  { name: 'Fern', colors: ['#15803D', '#22C55E', '#F0FDF4'],
    vars: { '--accent': '#15803D', '--accent-light': '#F0FDF4' },
    darkVars: { '--accent': '#22C55E', '--accent-light': '#14532D' } },
  { name: 'Pastel Pink', colors: ['#F9A8D4', '#FBCFE8', '#FDF2F8'],
    vars: { '--accent': '#EC4899', '--accent-light': '#FDF2F8' },
    darkVars: { '--accent': '#F9A8D4', '--accent-light': '#500724' } },
  { name: 'Pastel Green', colors: ['#86EFAC', '#BBF7D0', '#F0FDF4'],
    vars: { '--accent': '#4ADE80', '--accent-light': '#F0FDF4' },
    darkVars: { '--accent': '#86EFAC', '--accent-light': '#14532D' } },
  { name: 'Pastel Lilac', colors: ['#C4B5FD', '#DDD6FE', '#F5F3FF'],
    vars: { '--accent': '#A78BFA', '--accent-light': '#F5F3FF' },
    darkVars: { '--accent': '#C4B5FD', '--accent-light': '#3B0764' } },
  { name: 'Slate', colors: ['#475569', '#94A3B8', '#F8FAFC'], vars: { '--accent': '#475569', '--accent-light': '#F8FAFC' }, darkVars: { '--accent': '#94A3B8', '--accent-light': '#1E293B' } },
]

export interface FontGroup {
  group: string
  fonts: { name: string; family: string }[]
}

export const FONT_GROUPS: FontGroup[] = [
  { group: 'Sans-serif', fonts: [
    { name: 'System Default', family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif' },
    { name: 'Inter', family: '"Inter", sans-serif' },
    { name: 'Poppins', family: '"Poppins", sans-serif' },
    { name: 'DM Sans', family: '"DM Sans", sans-serif' },
    { name: 'Lexend', family: '"Lexend", sans-serif' },
    { name: 'Lato', family: '"Lato", sans-serif' },
    { name: 'Source Sans Pro', family: '"Source Sans 3", sans-serif' },
    { name: 'IBM Plex Sans', family: '"IBM Plex Sans", sans-serif' },
    { name: 'Raleway', family: '"Raleway", sans-serif' },
    { name: 'Outfit', family: '"Outfit", sans-serif' },
    { name: 'Space Grotesk', family: '"Space Grotesk", sans-serif' },
    { name: 'Nunito', family: '"Nunito", sans-serif' },
    { name: 'Quicksand', family: '"Quicksand", sans-serif' },
    { name: 'Plus Jakarta Sans', family: '"Plus Jakarta Sans", sans-serif' },
    { name: 'Manrope', family: '"Manrope", sans-serif' },
    { name: 'Sora', family: '"Sora", sans-serif' },
  ]},
  { group: 'Serif', fonts: [
    { name: 'Georgia', family: 'Georgia, "Times New Roman", serif' },
    { name: 'Playfair Display', family: '"Playfair Display", serif' },
    { name: 'Merriweather', family: '"Merriweather", serif' },
    { name: 'Lora', family: '"Lora", serif' },
    { name: 'Fraunces', family: '"Fraunces", serif' },
    { name: 'Cormorant Garamond', family: '"Cormorant Garamond", serif' },
  ]},
  { group: 'Monospace', fonts: [
    { name: 'JetBrains Mono', family: '"JetBrains Mono", monospace' },
    { name: 'Fira Code', family: '"Fira Code", monospace' },
    { name: 'Source Code Pro', family: '"Source Code Pro", monospace' },
    { name: 'Geist Mono', family: '"Geist Mono", monospace' },
    { name: 'Inconsolata', family: '"Inconsolata", monospace' },
  ]},
]

export const GOOGLE_FONTS_URL = 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&family=DM+Sans:wght@400;500;600;700&family=Lexend:wght@400;500;600;700&family=Lato:wght@400;700&family=Source+Sans+3:wght@400;600;700&family=IBM+Plex+Sans:wght@400;500;600;700&family=Raleway:wght@400;500;600;700&family=Outfit:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&family=Playfair+Display:wght@400;600;700&family=Merriweather:wght@400;700&family=Lora:wght@400;600;700&family=JetBrains+Mono:wght@400;500;700&family=Fira+Code:wght@400;500;700&family=Source+Code+Pro:wght@400;600;700&family=Nunito:wght@400;600;700&family=Quicksand:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700&family=Sora:wght@400;500;600;700&family=Fraunces:wght@400;600;700&family=Cormorant+Garamond:wght@400;600;700&family=Inconsolata:wght@400;500;700&display=swap'
